Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 1,334,244,114 milliseconds ago.  The last packet sent successfully to the server was 1,334,244,115 milliseconds ago. is longer than the server configured value of 'wait\_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

